# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    stijn:
                        password: $2y$12$SXu9uAKi.ALC9R3jC0MpceYgmcSlx36DEbbNVHPnDk95W0WQMIkci
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$.PWS7nFkfI32MTwbpt4p.OJra2GnD64YIHpZzx1BQU3zKMKc5TO56
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_USER] }

    encoders:
        Symfony\Component\Security\Core\User\User:
                    algorithm: bcrypt
                    cost: 12